---
title: "Research"
output:
  html_document:
    df_print: paged
    toc: no
    toc_float:
      collapsed: no
      smooth_scroll: no
---

<style type="text/css">
  body{
  font-size: 13pt;
}
</style>


<br>
<br>


In my work, I study the _neural_, _psychological_, and _social network_ factors that underlie social risk taking in adolescents and young adults.

<br>

### 1. What is social risk taking?
<br>

Many of our life decisions happen at the intersection of social and risk taking. For example, reaching out to talk with a stranger may bring the rewarding experience of having a great conversation, but also carries the inherent risk of being rejected or negatively judged. 

This line of study investigates the neuropsychological processes supporting conformity and resistance to risky social influence. In one study (Pei et al., 2020), we found that adolescents’ neural responses to risk taking may modulate their conformity to different types of peer influence. Findings from this study suggested that the VS may act in concert with other cortical regions to protect against harmful peer influence. 

<br>

### 2. Social risk taking and social networks


### 3. Promoting social risk taking in adolescents
<br>

Adolescents across the world demonstrate increased risk taking behavior compared to adults. Although adolescent risk taking may lead to negative consequences such as motor vehicle accidents, tobacco use, and unsafe sexual behavior , recent studies highlight ways that risk taking during adolescence can be adaptive. Specifically, these studies indicate that increased risk taking behavior during adolescence is a normative developmental process that brings crucial opportunities for health promotion, academic achievements, social engagement, and life success (Crone & Dahl, 2012). As such, an important goal for parents, educators, and health practitioners is to effectively promote positive risk taking behaviors in adolescents.

<br>

This project focuses on one specific type of potentially positive risk taking behavior: social risk taking. First, social risk taking during adolescence is functionally adaptive as it facilitates the exploration of new social roles, creation of meaningful relationships, learning new skills, and engagement in other rewarding experiences; and 2) as adolescents start to spend more time with their friends than their parents, they are particularly sensitive to social cues (especially social rejection) and may particularly avoid social risk taking during this time period.

<br>

* Does our social network structure (i.e. clustering structure) influence risk taking behavior?

* Can we experimentally promote social risk taking in lab environment?